language: node_js
node_js:
  - "16.15.0",
  - "16.7"
sudo: required
services:
  - docker
before_install:
  - docker build -t ddvalim/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ddvalim/docker-react npm run test
deploy:
  provider: heroku
  api_key:
    - secure: $SECURE_KEY
  app: "ddvalim-docker-react"
  on:
    branch: master